codecov:
  require_ci_to_pass: yes
  branch: master

ignore:
  - "tests"
  - "extern"
  - "examples"
  - "setup.py" 
  - "publish.py" 

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  
  status:
    project: # settings affecting project coverage
      enabled: yes
      target: auto # auto % coverage target
      threshold: 5%  # allow for 5% reduction of coverage without failing

    # do not run coverage on patch nor changes
    patch: no
